# Generated by Django 5.2 on 2025-04-04 14:05

from django.db import migrations
import os # Import os to access environment variables
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()
    
    # Use environment variables or fallback defaults
    DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin')
    DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@example.com')
    DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'complexpassword123') # CHANGE THIS!

    if not User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        print(f'\nCreating superuser: {DJANGO_SUPERUSER_USERNAME}')
        User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            email=DJANGO_SUPERUSER_EMAIL,
            password=DJANGO_SUPERUSER_PASSWORD
        )
    else:
        print(f'\nSuperuser {DJANGO_SUPERUSER_USERNAME} already exists.')

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_stock_alter_product_image'),
        # Add dependency on auth app's initial migration if needed
        # ('auth', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
